import type {
  Product,
  Order,
  Dispatch,
  Driver,
  Vendor,
  DashboardStats,
  Notification,
  ApprovalRequest,
  TeamMember,
} from '@/types';

// ---- Mock Products ----
export const mockProducts: Product[] = [
  {
    id: 'prod_001',
    name: 'DeWalt 20V MAX XR Hammer Drill Kit',
    slug: 'dewalt-20v-max-xr-hammer-drill',
    description: 'High-performance brushless hammer drill with 3-speed settings. Includes two 5.0Ah batteries, charger, and hard case. Perfect for concrete, masonry, and heavy-duty drilling applications.',
    short_description: 'Brushless hammer drill with 3-speed settings',
    sku: 'DW-HMD-20V-XR',
    brand: 'DeWalt',
    category: 'power_tools',
    images: ['/images/products/hammer-drill.jpg'],
    price: 299.99,
    compare_at_price: 349.99,
    currency: 'USD',
    is_rentable: true,
    rental_prices: [
      { period: 'hourly', price: 15, deposit: 100 },
      { period: 'daily', price: 45, deposit: 100 },
      { period: 'weekly', price: 175, deposit: 150 },
    ],
    weight_lbs: 8.5,
    dimensions: { length: 14, width: 10, height: 5 },
    specifications: { 'Chuck Size': '1/2"', 'Max RPM': '2,250', 'Battery': '20V 5.0Ah', 'Torque': '700 in-lbs' },
    tags: ['drill', 'hammer drill', 'cordless', 'brushless', 'dewalt'],
    vendor_id: 'vendor_001',
    vendor_name: 'Pro Tool Supply',
    rating: 4.8,
    review_count: 342,
    in_stock: true,
    stock_quantity: 24,
    min_order_quantity: 1,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 45,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-03-28T14:30:00Z',
  },
  {
    id: 'prod_002',
    name: 'Milwaukee M18 FUEL Circular Saw',
    slug: 'milwaukee-m18-fuel-circular-saw',
    description: 'The M18 FUEL 7-1/4" Circular Saw delivers the power of a 15A corded saw. POWERSTATE brushless motor maintains speed under load for the fastest cuts in wood.',
    short_description: '7-1/4" cordless circular saw with brushless motor',
    sku: 'MIL-CS-M18-FUEL',
    brand: 'Milwaukee',
    category: 'power_tools',
    images: ['/images/products/circular-saw.jpg'],
    price: 249.00,
    compare_at_price: 279.00,
    currency: 'USD',
    is_rentable: true,
    rental_prices: [
      { period: 'daily', price: 40, deposit: 100 },
      { period: 'weekly', price: 150, deposit: 150 },
    ],
    weight_lbs: 7.2,
    specifications: { 'Blade Size': '7-1/4"', 'Max RPM': '5,800', 'Cut Depth': '2-1/2"', 'Battery': 'M18' },
    tags: ['saw', 'circular saw', 'cordless', 'milwaukee'],
    vendor_id: 'vendor_001',
    vendor_name: 'Pro Tool Supply',
    rating: 4.7,
    review_count: 218,
    in_stock: true,
    stock_quantity: 12,
    min_order_quantity: 1,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 45,
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-03-25T09:00:00Z',
  },
  {
    id: 'prod_003',
    name: 'Fluke 117 Electricians True RMS Multimeter',
    slug: 'fluke-117-multimeter',
    description: 'The Fluke 117 is the ideal multimeter for electricians. Features non-contact voltage detection, AutoVolt automatic AC/DC voltage selection, and a large white LED backlight.',
    short_description: 'True RMS multimeter with non-contact voltage detection',
    sku: 'FLK-117-ELEC',
    brand: 'Fluke',
    category: 'electrical',
    images: ['/images/products/multimeter.jpg'],
    price: 219.99,
    currency: 'USD',
    is_rentable: true,
    rental_prices: [
      { period: 'daily', price: 25, deposit: 75 },
      { period: 'weekly', price: 95, deposit: 100 },
    ],
    weight_lbs: 1.3,
    specifications: { 'AC Voltage': '600V', 'DC Voltage': '600V', 'Resistance': '40MΩ', 'Safety': 'CAT III 600V' },
    tags: ['multimeter', 'fluke', 'electrical', 'testing', 'measurement'],
    vendor_id: 'vendor_002',
    vendor_name: 'ElectroParts Direct',
    rating: 4.9,
    review_count: 567,
    in_stock: true,
    stock_quantity: 35,
    min_order_quantity: 1,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 30,
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 'prod_004',
    name: 'Copper Pipe 1/2" x 10ft Type L',
    slug: 'copper-pipe-half-inch-10ft',
    description: 'Type L copper pipe, 1/2 inch diameter, 10 foot length. Ideal for water supply lines, HVAC refrigerant lines, and general plumbing.',
    short_description: '1/2" x 10ft Type L copper pipe',
    sku: 'CP-L-05-10',
    brand: 'Mueller',
    category: 'plumbing',
    images: ['/images/products/copper-pipe.jpg'],
    price: 42.50,
    currency: 'USD',
    is_rentable: false,
    weight_lbs: 3.2,
    specifications: { 'Diameter': '1/2"', 'Length': '10 ft', 'Type': 'L', 'Wall Thickness': '0.040"' },
    tags: ['copper', 'pipe', 'plumbing', 'water supply'],
    vendor_id: 'vendor_003',
    vendor_name: 'BuildRight Materials',
    rating: 4.5,
    review_count: 89,
    in_stock: true,
    stock_quantity: 200,
    min_order_quantity: 1,
    max_order_quantity: 50,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 60,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-03-28T10:00:00Z',
  },
  {
    id: 'prod_005',
    name: 'Hilti TE 70-ATC/AVR Rotary Hammer',
    slug: 'hilti-te-70-rotary-hammer',
    description: 'Heavy-duty combihammer for drilling and chiseling in concrete and masonry. Features Active Torque Control and Active Vibration Reduction for maximum safety and comfort.',
    short_description: 'Heavy-duty rotary hammer for concrete and masonry',
    sku: 'HLT-TE70-ATC',
    brand: 'Hilti',
    category: 'power_tools',
    images: ['/images/products/rotary-hammer.jpg'],
    price: 1899.00,
    currency: 'USD',
    is_rentable: true,
    rental_prices: [
      { period: 'hourly', price: 35, deposit: 500 },
      { period: 'daily', price: 125, deposit: 500 },
      { period: 'weekly', price: 450, deposit: 750 },
      { period: 'monthly', price: 1200, deposit: 1000 },
    ],
    weight_lbs: 15.4,
    specifications: { 'Impact Energy': '8.5 ft-lbs', 'Drilling Range': '5/8"-2"', 'Chisel Rate': '2,760 BPM' },
    tags: ['rotary hammer', 'hilti', 'concrete', 'demolition', 'heavy duty'],
    vendor_id: 'vendor_001',
    vendor_name: 'Pro Tool Supply',
    rating: 4.9,
    review_count: 156,
    in_stock: true,
    stock_quantity: 5,
    min_order_quantity: 1,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 60,
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-03-30T10:00:00Z',
  },
  {
    id: 'prod_006',
    name: 'CAT6A Plenum Cable 1000ft Box',
    slug: 'cat6a-plenum-cable-1000ft',
    description: 'CAT6A plenum-rated cable for commercial network installations. 23AWG solid copper conductors. Supports 10G Ethernet up to 100 meters. UL Listed and ETL Verified.',
    short_description: '1000ft CAT6A plenum-rated network cable',
    sku: 'NET-C6A-PL-1000',
    brand: 'Belden',
    category: 'networking',
    images: ['/images/products/cat6a-cable.jpg'],
    price: 389.99,
    currency: 'USD',
    is_rentable: false,
    weight_lbs: 35,
    specifications: { 'Category': '6A', 'Length': '1000 ft', 'Rating': 'Plenum (CMP)', 'Conductor': '23AWG Solid' },
    tags: ['cat6a', 'network cable', 'plenum', 'ethernet', 'data center'],
    vendor_id: 'vendor_002',
    vendor_name: 'ElectroParts Direct',
    rating: 4.6,
    review_count: 203,
    in_stock: true,
    stock_quantity: 45,
    min_order_quantity: 1,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 55,
    created_at: '2026-01-25T10:00:00Z',
    updated_at: '2026-03-22T10:00:00Z',
  },
  {
    id: 'prod_007',
    name: 'Klein Tools 11-in-1 Screwdriver/Nut Driver',
    slug: 'klein-11-in-1-screwdriver',
    description: 'Multi-bit screwdriver and nut driver set in one compact tool. Cushion-grip handle for comfort and torque. Includes Phillips, slotted, square, Torx, and nut driver tips.',
    short_description: '11-in-1 multi-bit screwdriver/nut driver',
    sku: 'KLN-32500-11',
    brand: 'Klein Tools',
    category: 'hand_tools',
    images: ['/images/products/multi-screwdriver.jpg'],
    price: 24.97,
    currency: 'USD',
    is_rentable: false,
    weight_lbs: 0.6,
    specifications: { 'Tips Included': '11', 'Handle': 'Cushion-Grip', 'Length': '7.5"', 'Material': 'Chrome Vanadium' },
    tags: ['screwdriver', 'nut driver', 'multi-tool', 'klein', 'hand tool'],
    vendor_id: 'vendor_003',
    vendor_name: 'BuildRight Materials',
    rating: 4.7,
    review_count: 1245,
    in_stock: true,
    stock_quantity: 150,
    min_order_quantity: 1,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 25,
    created_at: '2026-01-05T10:00:00Z',
    updated_at: '2026-03-29T10:00:00Z',
  },
  {
    id: 'prod_008',
    name: 'Generac GP3600 Portable Generator',
    slug: 'generac-gp3600-generator',
    description: '3600-watt portable generator with 212cc OHV engine. PowerRush Advanced Technology delivers over 25% more starting capacity. Ideal for job sites and emergency power.',
    short_description: '3600W portable generator for job sites',
    sku: 'GEN-GP3600',
    brand: 'Generac',
    category: 'power_tools',
    images: ['/images/products/generator.jpg'],
    price: 549.00,
    compare_at_price: 629.00,
    currency: 'USD',
    is_rentable: true,
    rental_prices: [
      { period: 'daily', price: 75, deposit: 200 },
      { period: 'weekly', price: 275, deposit: 300 },
      { period: 'monthly', price: 750, deposit: 500 },
    ],
    weight_lbs: 102,
    specifications: { 'Wattage': '3,600W Running / 4,500W Starting', 'Fuel': 'Gasoline', 'Runtime': '10.75 hrs @ 50%' },
    tags: ['generator', 'portable power', 'job site', 'generac'],
    vendor_id: 'vendor_001',
    vendor_name: 'Pro Tool Supply',
    rating: 4.4,
    review_count: 98,
    in_stock: true,
    stock_quantity: 8,
    min_order_quantity: 1,
    is_urgent_eligible: false,
    estimated_delivery_minutes: 90,
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-03-27T10:00:00Z',
  },
  {
    id: 'prod_009',
    name: 'Simpson Strong-Tie Structural Screws (50-Pack)',
    slug: 'simpson-structural-screws-50pk',
    description: 'SD Connector structural wood screws. No predrilling required. ICC-ES evaluated. Mechanically galvanized for corrosion resistance. Replaces 10d nails in connector installations.',
    short_description: 'Structural wood screws, 50-pack, #9 x 1-1/2"',
    sku: 'SST-SD9112-50',
    brand: 'Simpson Strong-Tie',
    category: 'fasteners',
    images: ['/images/products/structural-screws.jpg'],
    price: 14.98,
    currency: 'USD',
    is_rentable: false,
    weight_lbs: 1.1,
    specifications: { 'Size': '#9 x 1-1/2"', 'Quantity': '50', 'Coating': 'Mechanically Galvanized', 'Head': 'Hex Washer' },
    tags: ['screws', 'structural', 'simpson', 'fastener', 'wood'],
    vendor_id: 'vendor_003',
    vendor_name: 'BuildRight Materials',
    rating: 4.8,
    review_count: 876,
    in_stock: true,
    stock_quantity: 500,
    min_order_quantity: 1,
    max_order_quantity: 100,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 20,
    created_at: '2026-01-02T10:00:00Z',
    updated_at: '2026-03-30T10:00:00Z',
  },
  {
    id: 'prod_010',
    name: '3M Full Face Respirator 6900 (Large)',
    slug: '3m-full-face-respirator-6900',
    description: 'Full facepiece reusable respirator with silicone face seal. Bayonet compatible with 3M cartridges and filters. Wide field of view with scratch-resistant lens.',
    short_description: 'Full face reusable respirator, large',
    sku: '3M-6900-LG',
    brand: '3M',
    category: 'safety_equipment',
    images: ['/images/products/respirator.jpg'],
    price: 159.99,
    currency: 'USD',
    is_rentable: false,
    weight_lbs: 1.0,
    specifications: { 'Size': 'Large', 'Material': 'Silicone', 'Certification': 'NIOSH', 'Lens': 'Polycarbonate' },
    tags: ['respirator', '3m', 'safety', 'ppe', 'full face'],
    vendor_id: 'vendor_001',
    vendor_name: 'Pro Tool Supply',
    rating: 4.6,
    review_count: 312,
    in_stock: true,
    stock_quantity: 42,
    min_order_quantity: 1,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 35,
    created_at: '2026-01-18T10:00:00Z',
    updated_at: '2026-03-26T10:00:00Z',
  },
  {
    id: 'prod_011',
    name: 'Ridgid K-400 Drum Machine Drain Cleaner',
    slug: 'ridgid-k400-drain-cleaner',
    description: 'Professional drain cleaning machine for 1-1/2" to 4" drain lines. 375 RPM autofeed. Includes 75ft of 3/8" cable with funnel auger. Built-in GFCI for safety.',
    short_description: 'Professional drain cleaning machine',
    sku: 'RDG-K400-AF',
    brand: 'Ridgid',
    category: 'plumbing',
    images: ['/images/products/drain-cleaner.jpg'],
    price: 849.00,
    currency: 'USD',
    is_rentable: true,
    rental_prices: [
      { period: 'hourly', price: 25, deposit: 200 },
      { period: 'daily', price: 85, deposit: 300 },
      { period: 'weekly', price: 325, deposit: 400 },
    ],
    weight_lbs: 52,
    specifications: { 'Drain Size': '1-1/2" to 4"', 'Cable': '75ft x 3/8"', 'RPM': '375', 'Motor': '1/3 HP' },
    tags: ['drain cleaner', 'plumbing', 'ridgid', 'snake', 'professional'],
    vendor_id: 'vendor_003',
    vendor_name: 'BuildRight Materials',
    rating: 4.5,
    review_count: 67,
    in_stock: true,
    stock_quantity: 3,
    min_order_quantity: 1,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 75,
    created_at: '2026-02-20T10:00:00Z',
    updated_at: '2026-03-29T10:00:00Z',
  },
  {
    id: 'prod_012',
    name: 'Fiber Optic Fusion Splicer Kit',
    slug: 'fiber-optic-fusion-splicer-kit',
    description: 'Core alignment fusion splicer with 6-motor alignment system. 7s splicing, 28s heating. 5" touchscreen, 5000 splice image storage. Includes cleaver, stripper, and carrying case.',
    short_description: 'Core alignment fiber optic fusion splicer',
    sku: 'FO-SPLICE-6M',
    brand: 'Signalfire',
    category: 'telecom',
    images: ['/images/products/fusion-splicer.jpg'],
    price: 2499.00,
    currency: 'USD',
    is_rentable: true,
    rental_prices: [
      { period: 'daily', price: 150, deposit: 1000 },
      { period: 'weekly', price: 550, deposit: 1500 },
      { period: 'monthly', price: 1500, deposit: 2000 },
    ],
    weight_lbs: 4.8,
    specifications: { 'Alignment': '6-Motor Core', 'Splice Time': '7 sec', 'Heat Time': '28 sec', 'Fiber Types': 'SM/MM/DS/NZDS' },
    tags: ['fiber optic', 'splicer', 'telecom', 'fusion', 'networking'],
    vendor_id: 'vendor_002',
    vendor_name: 'ElectroParts Direct',
    rating: 4.3,
    review_count: 41,
    in_stock: true,
    stock_quantity: 6,
    min_order_quantity: 1,
    is_urgent_eligible: true,
    estimated_delivery_minutes: 65,
    created_at: '2026-02-05T10:00:00Z',
    updated_at: '2026-03-28T10:00:00Z',
  },
];

// ---- Mock Vendors ----
export const mockVendors: Vendor[] = [
  {
    id: 'vendor_001',
    user_id: 'user_v1',
    company_name: 'Pro Tool Supply',
    description: 'Professional tool supplier serving contractors and tradespeople. Wide selection of power tools, hand tools, and safety equipment from top brands.',
    business_type: 'retailer',
    categories: ['power_tools', 'hand_tools', 'safety_equipment'],
    address: { street: '1250 Industrial Blvd', city: 'Houston', state: 'TX', zip: '77001', country: 'US', lat: 29.7604, lng: -95.3698 },
    service_radius_miles: 35,
    operating_hours: [
      { day: 'monday', open: '06:00', close: '20:00', is_closed: false },
      { day: 'tuesday', open: '06:00', close: '20:00', is_closed: false },
      { day: 'wednesday', open: '06:00', close: '20:00', is_closed: false },
      { day: 'thursday', open: '06:00', close: '20:00', is_closed: false },
      { day: 'friday', open: '06:00', close: '20:00', is_closed: false },
      { day: 'saturday', open: '07:00', close: '18:00', is_closed: false },
      { day: 'sunday', open: '08:00', close: '14:00', is_closed: false },
    ],
    rating: 4.8,
    total_orders: 12450,
    fulfillment_speed_avg_minutes: 38,
    is_verified: true,
    is_active: true,
    commission_rate: 12,
    bank_account_connected: true,
    created_at: '2025-06-01T10:00:00Z',
  },
  {
    id: 'vendor_002',
    user_id: 'user_v2',
    company_name: 'ElectroParts Direct',
    description: 'Specialized distributor for electrical components, test equipment, telecom supplies, and networking infrastructure.',
    business_type: 'distributor',
    categories: ['electrical', 'telecom', 'networking'],
    address: { street: '890 Tech Park Dr', city: 'Dallas', state: 'TX', zip: '75201', country: 'US', lat: 32.7767, lng: -96.797 },
    service_radius_miles: 50,
    operating_hours: [
      { day: 'monday', open: '07:00', close: '19:00', is_closed: false },
      { day: 'tuesday', open: '07:00', close: '19:00', is_closed: false },
      { day: 'wednesday', open: '07:00', close: '19:00', is_closed: false },
      { day: 'thursday', open: '07:00', close: '19:00', is_closed: false },
      { day: 'friday', open: '07:00', close: '19:00', is_closed: false },
      { day: 'saturday', open: '08:00', close: '16:00', is_closed: false },
      { day: 'sunday', open: '08:00', close: '16:00', is_closed: true },
    ],
    rating: 4.7,
    total_orders: 8920,
    fulfillment_speed_avg_minutes: 32,
    is_verified: true,
    is_active: true,
    commission_rate: 10,
    bank_account_connected: true,
    created_at: '2025-07-15T10:00:00Z',
  },
  {
    id: 'vendor_003',
    user_id: 'user_v3',
    company_name: 'BuildRight Materials',
    description: 'Full-service building materials supplier. Lumber, plumbing, fasteners, and general construction materials with same-day delivery.',
    business_type: 'wholesaler',
    categories: ['plumbing', 'fasteners', 'lumber', 'concrete'],
    address: { street: '4500 Warehouse Row', city: 'Austin', state: 'TX', zip: '78701', country: 'US', lat: 30.2672, lng: -97.7431 },
    service_radius_miles: 40,
    operating_hours: [
      { day: 'monday', open: '05:30', close: '19:00', is_closed: false },
      { day: 'tuesday', open: '05:30', close: '19:00', is_closed: false },
      { day: 'wednesday', open: '05:30', close: '19:00', is_closed: false },
      { day: 'thursday', open: '05:30', close: '19:00', is_closed: false },
      { day: 'friday', open: '05:30', close: '19:00', is_closed: false },
      { day: 'saturday', open: '06:00', close: '17:00', is_closed: false },
      { day: 'sunday', open: '06:00', close: '17:00', is_closed: true },
    ],
    rating: 4.6,
    total_orders: 15780,
    fulfillment_speed_avg_minutes: 42,
    is_verified: true,
    is_active: true,
    commission_rate: 8,
    bank_account_connected: true,
    created_at: '2025-05-10T10:00:00Z',
  },
];

// ---- Mock Orders ----
export const mockOrders: Order[] = [
  {
    id: 'ord_001',
    order_number: 'DRM-LK82F-X9A3',
    user_id: 'user_001',
    vendor_id: 'vendor_001',
    vendor_name: 'Pro Tool Supply',
    status: 'in_transit',
    priority: 'urgent',
    fulfillment_type: 'buy',
    items: [
      { id: 'oi_001', product_id: 'prod_001', product_name: 'DeWalt 20V MAX XR Hammer Drill Kit', product_image: '/images/products/hammer-drill.jpg', sku: 'DW-HMD-20V-XR', quantity: 1, unit_price: 299.99, total_price: 299.99, fulfillment_type: 'buy' },
    ],
    subtotal: 299.99,
    tax: 24.75,
    delivery_fee: 12.99,
    urgent_fee: 15.00,
    total: 352.73,
    currency: 'USD',
    payment_status: 'captured',
    payment_method: 'card',
    delivery_address: { street: '742 Evergreen Terrace', city: 'Houston', state: 'TX', zip: '77002', country: 'US', lat: 29.762, lng: -95.367 },
    delivery_method: 'third_party_courier',
    estimated_delivery_at: '2026-04-01T15:30:00Z',
    dispatch_id: 'dsp_001',
    driver_id: 'driver_001',
    approval_required: false,
    job_site_name: 'Westfield Tower - Floor 12',
    project_reference: 'PRJ-2026-0142',
    notes: 'Leave with site foreman if I am not at the entrance',
    created_at: '2026-04-01T13:45:00Z',
    updated_at: '2026-04-01T14:20:00Z',
  },
  {
    id: 'ord_002',
    order_number: 'DRM-MN47K-B2C1',
    user_id: 'user_001',
    vendor_id: 'vendor_002',
    vendor_name: 'ElectroParts Direct',
    status: 'delivered',
    priority: 'critical',
    fulfillment_type: 'buy',
    items: [
      { id: 'oi_002', product_id: 'prod_003', product_name: 'Fluke 117 Electricians True RMS Multimeter', product_image: '/images/products/multimeter.jpg', sku: 'FLK-117-ELEC', quantity: 2, unit_price: 219.99, total_price: 439.98, fulfillment_type: 'buy' },
      { id: 'oi_003', product_id: 'prod_006', product_name: 'CAT6A Plenum Cable 1000ft Box', product_image: '/images/products/cat6a-cable.jpg', sku: 'NET-C6A-PL-1000', quantity: 3, unit_price: 389.99, total_price: 1169.97, fulfillment_type: 'buy' },
    ],
    subtotal: 1609.95,
    tax: 132.82,
    delivery_fee: 24.99,
    urgent_fee: 35.00,
    total: 1802.76,
    currency: 'USD',
    payment_status: 'captured',
    payment_method: 'company_account',
    delivery_address: { street: '100 Data Center Pkwy', city: 'Dallas', state: 'TX', zip: '75201', country: 'US', lat: 32.78, lng: -96.80 },
    delivery_method: 'internal_driver',
    estimated_delivery_at: '2026-03-31T16:00:00Z',
    actual_delivery_at: '2026-03-31T15:42:00Z',
    approval_required: true,
    approved_by: 'user_mgr_001',
    approved_at: '2026-03-31T13:15:00Z',
    job_site_name: 'Lone Star Data Center',
    project_reference: 'DC-EXPANSION-Q2',
    created_at: '2026-03-31T12:30:00Z',
    updated_at: '2026-03-31T15:42:00Z',
  },
  {
    id: 'ord_003',
    order_number: 'DRM-PQ29R-T5F8',
    user_id: 'user_001',
    vendor_id: 'vendor_003',
    vendor_name: 'BuildRight Materials',
    status: 'pending_approval',
    priority: 'standard',
    fulfillment_type: 'rent',
    items: [
      { id: 'oi_004', product_id: 'prod_011', product_name: 'Ridgid K-400 Drum Machine Drain Cleaner', product_image: '/images/products/drain-cleaner.jpg', sku: 'RDG-K400-AF', quantity: 1, unit_price: 85, total_price: 85, fulfillment_type: 'rent', rental_period: 'daily', rental_start: '2026-04-03T08:00:00Z', rental_end: '2026-04-03T18:00:00Z', rental_deposit: 300 },
    ],
    subtotal: 85.00,
    tax: 7.01,
    delivery_fee: 9.99,
    urgent_fee: 0,
    total: 401.00,
    currency: 'USD',
    payment_status: 'authorized',
    payment_method: 'card',
    delivery_address: { street: '555 Elm Street', city: 'Austin', state: 'TX', zip: '78702', country: 'US' },
    delivery_method: 'customer_pickup',
    approval_required: true,
    notes: 'Need for emergency drain repair at residential property',
    created_at: '2026-04-01T09:00:00Z',
    updated_at: '2026-04-01T09:00:00Z',
  },
  {
    id: 'ord_004',
    order_number: 'DRM-AB12C-D3E4',
    user_id: 'user_001',
    vendor_id: 'vendor_001',
    vendor_name: 'Pro Tool Supply',
    status: 'preparing',
    priority: 'urgent',
    fulfillment_type: 'buy',
    items: [
      { id: 'oi_005', product_id: 'prod_010', product_name: '3M Full Face Respirator 6900 (Large)', product_image: '/images/products/respirator.jpg', sku: '3M-6900-LG', quantity: 4, unit_price: 159.99, total_price: 639.96, fulfillment_type: 'buy' },
      { id: 'oi_006', product_id: 'prod_007', product_name: 'Klein Tools 11-in-1 Screwdriver/Nut Driver', product_image: '/images/products/multi-screwdriver.jpg', sku: 'KLN-32500-11', quantity: 6, unit_price: 24.97, total_price: 149.82, fulfillment_type: 'buy' },
    ],
    subtotal: 789.78,
    tax: 65.16,
    delivery_fee: 14.99,
    urgent_fee: 20.00,
    total: 889.93,
    currency: 'USD',
    payment_status: 'captured',
    payment_method: 'po_number',
    delivery_address: { street: '2200 Construction Ave', city: 'Houston', state: 'TX', zip: '77003', country: 'US' },
    delivery_method: 'warehouse_runner',
    estimated_delivery_at: '2026-04-01T16:45:00Z',
    approval_required: false,
    job_site_name: 'Memorial Park Renovation',
    project_reference: 'MPR-2026-008',
    created_at: '2026-04-01T14:00:00Z',
    updated_at: '2026-04-01T14:30:00Z',
  },
];

// ---- Mock Dispatches ----
export const mockDispatches: Dispatch[] = [
  {
    id: 'dsp_001',
    order_id: 'ord_001',
    driver_id: 'driver_001',
    driver_name: 'Marcus Johnson',
    driver_phone: '+1-713-555-0142',
    driver_avatar: '/images/drivers/marcus.jpg',
    vehicle_type: 'Van',
    vehicle_plate: 'TX-PRO-4281',
    status: 'en_route_to_delivery',
    delivery_method: 'third_party_courier',
    pickup_address: { street: '1250 Industrial Blvd', city: 'Houston', state: 'TX', zip: '77001', country: 'US', lat: 29.7604, lng: -95.3698 },
    delivery_address: { street: '742 Evergreen Terrace', city: 'Houston', state: 'TX', zip: '77002', country: 'US', lat: 29.762, lng: -95.367 },
    pickup_eta_minutes: 0,
    delivery_eta_minutes: 12,
    distance_miles: 4.2,
    current_location: { lat: 29.7612, lng: -95.3685, heading: 45, speed: 28, timestamp: 1743548400000 },
    picked_up_at: '2026-04-01T14:15:00Z',
    created_at: '2026-04-01T13:50:00Z',
    updated_at: '2026-04-01T14:20:00Z',
  },
];

// ---- Mock Drivers ----
export const mockDrivers: Driver[] = [
  {
    id: 'driver_001',
    user_id: 'user_d1',
    full_name: 'Marcus Johnson',
    phone: '+1-713-555-0142',
    avatar_url: '/images/drivers/marcus.jpg',
    vehicle_type: 'van',
    vehicle_make: 'Ford',
    vehicle_model: 'Transit 250',
    vehicle_plate: 'TX-PRO-4281',
    license_number: 'DL-TX-28491',
    is_active: true,
    is_available: false,
    current_location: { lat: 29.7612, lng: -95.3685, heading: 45, speed: 28, timestamp: 1743548400000 },
    rating: 4.9,
    total_deliveries: 1247,
    service_area_miles: 30,
    max_weight_lbs: 500,
    created_at: '2025-08-10T10:00:00Z',
  },
  {
    id: 'driver_002',
    user_id: 'user_d2',
    full_name: 'Sarah Chen',
    phone: '+1-713-555-0198',
    vehicle_type: 'car',
    vehicle_make: 'Toyota',
    vehicle_model: 'RAV4',
    vehicle_plate: 'TX-DRM-7763',
    license_number: 'DL-TX-55102',
    is_active: true,
    is_available: true,
    current_location: { lat: 29.755, lng: -95.370, heading: 180, speed: 0, timestamp: 1743548400000 },
    rating: 4.8,
    total_deliveries: 892,
    service_area_miles: 25,
    max_weight_lbs: 150,
    created_at: '2025-09-20T10:00:00Z',
  },
  {
    id: 'driver_003',
    user_id: 'user_d3',
    full_name: 'James Rodriguez',
    phone: '+1-713-555-0234',
    vehicle_type: 'truck',
    vehicle_make: 'Chevrolet',
    vehicle_model: 'Silverado 2500',
    vehicle_plate: 'TX-HVY-1129',
    license_number: 'DL-TX-77830',
    is_active: true,
    is_available: true,
    current_location: { lat: 29.770, lng: -95.360, heading: 270, speed: 0, timestamp: 1743548400000 },
    rating: 4.7,
    total_deliveries: 2103,
    service_area_miles: 50,
    max_weight_lbs: 2000,
    created_at: '2025-07-05T10:00:00Z',
  },
];

// ---- Mock Team Members ----
export const mockTeamMembers: TeamMember[] = [
  { id: 'tm_001', user_id: 'user_001', company_id: 'comp_001', full_name: 'You (Account Owner)', email: 'owner@company.com', role: 'owner', department: 'Management', requires_approval: false, approved_by_role: [], is_active: true, invited_at: '2025-06-01T10:00:00Z', joined_at: '2025-06-01T10:00:00Z' },
  { id: 'tm_002', user_id: 'user_002', company_id: 'comp_001', full_name: 'Mike Torres', email: 'mike@company.com', role: 'manager', department: 'Field Operations', spending_limit: 5000, requires_approval: false, approved_by_role: [], is_active: true, invited_at: '2025-07-10T10:00:00Z', joined_at: '2025-07-10T12:00:00Z' },
  { id: 'tm_003', user_id: 'user_003', company_id: 'comp_001', full_name: 'Lisa Park', email: 'lisa@company.com', role: 'dispatcher', department: 'Logistics', spending_limit: 2000, requires_approval: true, approved_by_role: ['manager', 'owner'], is_active: true, invited_at: '2025-08-01T10:00:00Z', joined_at: '2025-08-01T14:00:00Z' },
  { id: 'tm_004', user_id: 'user_004', company_id: 'comp_001', full_name: 'Carlos Vega', email: 'carlos@company.com', role: 'technician', department: 'HVAC', spending_limit: 500, requires_approval: true, approved_by_role: ['manager', 'owner'], is_active: true, invited_at: '2025-09-15T10:00:00Z', joined_at: '2025-09-15T16:00:00Z' },
  { id: 'tm_005', user_id: 'user_005', company_id: 'comp_001', full_name: 'Rachel Kim', email: 'rachel@company.com', role: 'technician', department: 'Electrical', spending_limit: 500, requires_approval: true, approved_by_role: ['manager', 'owner'], is_active: true, invited_at: '2025-10-01T10:00:00Z', joined_at: '2025-10-02T09:00:00Z' },
  { id: 'tm_006', user_id: 'user_006', company_id: 'comp_001', full_name: 'David Chen', email: 'david@company.com', role: 'admin', department: 'IT', requires_approval: false, approved_by_role: [], is_active: true, invited_at: '2025-06-15T10:00:00Z', joined_at: '2025-06-15T10:00:00Z' },
];

// ---- Mock Approval Requests ----
export const mockApprovals: ApprovalRequest[] = [
  {
    id: 'apr_001',
    order_id: 'ord_003',
    requested_by: 'user_004',
    requested_by_name: 'Carlos Vega',
    assigned_to: 'user_001',
    assigned_to_name: 'You',
    company_id: 'comp_001',
    status: 'pending',
    amount: 401.00,
    reason: 'Emergency drain repair at 555 Elm St. Customer has standing water and needs immediate service.',
    items_summary: '1x Ridgid K-400 Drain Cleaner (1-day rental)',
    priority: 'standard',
    created_at: '2026-04-01T09:00:00Z',
  },
  {
    id: 'apr_002',
    order_id: 'ord_005',
    requested_by: 'user_005',
    requested_by_name: 'Rachel Kim',
    assigned_to: 'user_001',
    assigned_to_name: 'You',
    company_id: 'comp_001',
    status: 'pending',
    amount: 2499.00,
    reason: 'Fiber splicer needed for data center expansion project. Current unit is out for calibration.',
    items_summary: '1x Fiber Optic Fusion Splicer Kit (1-week rental)',
    priority: 'urgent',
    created_at: '2026-04-01T10:30:00Z',
  },
];

// ---- Mock Notifications ----
export const mockNotifications: Notification[] = [
  { id: 'notif_001', user_id: 'user_001', type: 'order_dispatched', title: 'Order Dispatched', message: 'Your order DRM-LK82F-X9A3 is on its way. Driver Marcus is 12 minutes away.', is_read: false, created_at: '2026-04-01T14:20:00Z' },
  { id: 'notif_002', user_id: 'user_001', type: 'approval_requested', title: 'Approval Required', message: 'Carlos Vega requested approval for a $401.00 rental order.', is_read: false, created_at: '2026-04-01T09:00:00Z' },
  { id: 'notif_003', user_id: 'user_001', type: 'approval_requested', title: 'Urgent Approval', message: 'Rachel Kim needs a fiber splicer kit ($2,499) for the data center project.', is_read: false, created_at: '2026-04-01T10:30:00Z' },
  { id: 'notif_004', user_id: 'user_001', type: 'order_delivered', title: 'Order Delivered', message: 'Your order DRM-MN47K-B2C1 has been delivered to Lone Star Data Center.', is_read: true, created_at: '2026-03-31T15:42:00Z' },
  { id: 'notif_005', user_id: 'user_001', type: 'driver_nearby', title: 'Driver Nearby', message: 'Marcus Johnson is approaching your delivery location.', is_read: false, created_at: '2026-04-01T14:18:00Z' },
  { id: 'notif_006', user_id: 'user_001', type: 'rental_due', title: 'Rental Return Reminder', message: 'Your Hilti TE 70 rental is due for return tomorrow by 5:00 PM.', is_read: true, created_at: '2026-03-30T09:00:00Z' },
];

// ---- Mock Dashboard Stats ----
export const mockDashboardStats: DashboardStats = {
  total_orders: 247,
  active_orders: 3,
  completed_today: 5,
  pending_approvals: 2,
  total_spent: 48920.50,
  avg_delivery_time_minutes: 42,
  active_rentals: 2,
  active_drivers: 3,
  orders_trend: [
    { date: '2026-03-25', value: 8 },
    { date: '2026-03-26', value: 12 },
    { date: '2026-03-27', value: 6 },
    { date: '2026-03-28', value: 15 },
    { date: '2026-03-29', value: 9 },
    { date: '2026-03-30', value: 11 },
    { date: '2026-03-31', value: 14 },
    { date: '2026-04-01', value: 8 },
  ],
  spending_trend: [
    { date: '2026-03-25', value: 2450 },
    { date: '2026-03-26', value: 3800 },
    { date: '2026-03-27', value: 1200 },
    { date: '2026-03-28', value: 5600 },
    { date: '2026-03-29', value: 2100 },
    { date: '2026-03-30', value: 4300 },
    { date: '2026-03-31', value: 3900 },
    { date: '2026-04-01', value: 2800 },
  ],
  top_categories: [
    { category: 'Power Tools', count: 67, amount: 18500 },
    { category: 'Electrical', count: 52, amount: 12400 },
    { category: 'Networking', count: 38, amount: 8900 },
    { category: 'Plumbing', count: 31, amount: 4200 },
    { category: 'Safety Equipment', count: 28, amount: 3600 },
  ],
  delivery_performance: [
    { method: 'Third-Party Courier', avg_minutes: 35, count: 98 },
    { method: 'Internal Driver', avg_minutes: 28, count: 62 },
    { method: 'Warehouse Runner', avg_minutes: 22, count: 45 },
    { method: 'Customer Pickup', avg_minutes: 15, count: 32 },
    { method: 'Drone Delivery', avg_minutes: 18, count: 10 },
  ],
};
